controller_list:
  - name: kinova_arm/effort_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - kinova_arm_joint_1
      - kinova_arm_joint_2
      - kinova_arm_joint_3
      - kinova_arm_joint_4
      - kinova_arm_joint_5
      - kinova_arm_joint_6
      - kinova_arm_joint_7
  - name: kinova_arm/effort_finger_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true    
    joints:
      - kinova_arm_joint_finger_1
      - kinova_arm_joint_finger_2
      - kinova_arm_joint_finger_3
